version: '3.8'

name: desafio_vox
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio_vox_backend
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - desafio_vox_network
    volumes:
      - .:/app
  db:
    image: postgres:alpine
    container_name: desafio_vox_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    networks:
      - desafio_vox_network
networks:
  desafio_vox_network:
    driver: bridge